server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/day0803fenye?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 1234
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 10MB
  redis:
    host: localhost
    port: 6379
    password: 123456
mybatis:
  mapper-locations: classpath:mapping/**/*.xml
  type-aliases-package: com.zzb.shopping.model  #sql语句执行日志打印控制台


  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.example.springboot1.dao: debug

img:
  save-path: D:/img/ # 图片存储路径
  domain: http://localhost:80/ # 反向代理url

